version: 1.1.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
only_commits:
  message: /\[ci\]/
skip_commits:
  files:
    - docs/
    - PumpDefinitions/
    - '**/*.md'
    - '*.txt'
    - appveyor.yml
    - LICENSE.txt
    - '.gitignor'
before_build:
- cmd: nuget restore
build:
  project: FlowCalc.sln
  verbosity: minimal
after_build:
- cmd: 7z a FlowCalc-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\FlowCalc\bin\%CONFIGURATION%\*.exe %APPVEYOR_BUILD_FOLDER%\FlowCalc\bin\%CONFIGURATION%\*.dll %APPVEYOR_BUILD_FOLDER%\PumpDefinitions %APPVEYOR_BUILD_FOLDER%\FittingDefinitions %APPVEYOR_BUILD_FOLDER%\PumpDefinitionEditor\bin\%CONFIGURATION%\PumpDefinitionEditor.exe -r
artifacts:
- path: FlowCalc-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip
deploy:
- provider: GitHub
  description: "`FlowCalc-%CONFIGURATION%-%APPVEYOR_BUILD_VERSION%.zip` enthält die Anwendung (FlowCalc.exe) sowie benötigte Programmbibliotheken (.dll). Ebenfalls enthalten sind die verfügbaren Pumpen- und Fittingdefinitionen, in Form von Xml-Dateien (.xml).\n\nDie Anwendung `FlowCalc.exe` kann direkt gestartet werden.\n\n#### Last commit message\n%APPVEYOR_REPO_COMMIT_MESSAGE%"
  auth_token:
    secure: f6bHUrxjNRP23jMDGRd4QM2CFVCLYROeYndAlsXhdiPirrViZ2lgp+Vg79PuSDRT
  prerelease: true
  